#pragma once

#include <memory>
#include <string>
#include <vector>

#include "engine/plugin/iplugin.hpp"

namespace hibiki {

/**
 * @brief A premium real-time channel vocoder.
 *
 * It uses a 24-band bandpass filterbank to analyze a modulator signal
 * and apply its spectral envelope to a carrier signal. The carrier can
 * be supplied via sidechain or generated by an internal polyphonic synth.
 */
class BuiltinVocodey : public IPlugin {
 public:
  static constexpr int kTotalParams = 8;
  static constexpr const char* kPath = "builtin://vocodey";
  static constexpr const char* kName = "Vocodey";

  enum ParamId {
    PARAM_ATTACK = 0,  ///< Envelope follower attack time (0.001s to 0.1s)
    PARAM_DECAY = 1,   ///< Envelope follower decay/release time (0.01s to 2.0s)
    PARAM_BANDWIDTH =
        2,  ///< Band filter quality Q factor adjustment (0.5 to 10.0)
    PARAM_NOISE_BLEED = 3,  ///< Sibilance noise bleed ratio (0.0 to 1.0)
    PARAM_SYNTH_DETUNE =
        4,             ///< Internal carrier synth detune ratio (0.0 to 1.0)
    PARAM_DRY = 5,     ///< Dry modulator mix level (0.0 to 1.0)
    PARAM_WET = 6,     ///< Wet vocoded mix level (0.0 to 1.0)
    PARAM_VOLUME = 7,  ///< Master output volume (0.0 to 1.0)
  };

  /**
   * @brief Constructs a new BuiltinVocodey plugin.
   */
  BuiltinVocodey();

  /**
   * @brief Destructor.
   */
  ~BuiltinVocodey() override;

  // IPlugin interface
  bool load(const std::string& path, int plugin_index = 0,
            double sample_rate = 44100.0) override;
  void showEditor() override {}
  void stopEditor() override {}
  void process(float** inputs, float** outputs, int num_samples,
               const HostProcessContext& context,
               const std::vector<MidiNoteEvent>& events,
               float** sidechain = nullptr) override;
  int getParameterCount() const override;
  bool getParameterInfo(int index, VstParamInfo& info) const override;
  void setParameterValue(uint32_t id, double valueNormalized) override;
  double getParameterValue(uint32_t id) const override;
  const std::string& getName() const override;
  const std::string& getPath() const override;
  int getPluginIndex() const override;
  bool isInstrument() const override;

  // Parameter conversion helpers
  static float normToAttackS(double norm);
  static float normToDecayS(double norm);
  static float normToBandwidthQ(double norm);

 private:
  struct Impl;
  std::unique_ptr<Impl> impl_;
};

}  // namespace hibiki
