namespace hibiki.project;

table Parameter {
    id: uint;
    value: float;
}

table Plugin {
    path: string;
    index: int;
    parameters: [Parameter];
}

enum ClipType : byte { MIDI = 0, AUDIO = 1 }

table Clip {
    slot_index: int;
    path: string;
    is_loop: bool = false;
    type: ClipType = MIDI;
}

table TimelineClip {
    path: string;
    start_time: float;
    duration: float;
}

table Track {
    index: int;
    name: string;  // User-defined track name
    plugins: [Plugin];
    clips: [Clip];
    timeline_clips: [TimelineClip];
}

table Project {
    bpm: float = 120.0;
    playhead_pos: float = 0.0;
    tracks: [Track];
}

root_type Project;
