package(default_visibility = ["//visibility:public"])

filegroup(
    name = "gradle_files",
    srcs = [
        "build.gradle",
        "gradle.properties",
        "gradle/wrapper/gradle-wrapper.jar",
        "gradle/wrapper/gradle-wrapper.properties",
        "gradlew",
        "settings.gradle",
    ],
)
