package(default_visibility = ["//visibility:public"])

exports_files([
    "build_android_apk.sh",
    "run_android_app.sh",
    "start_android_emulator.sh",
    "setup_android_sdk.sh",
    "format.sh",
])
